### ISSUE TITLE
Wrong output in 'Export Classifier Result' .csv file

### ISSUE THREAD

**Issue by loicsauteur** [fractal-napari-plugins-collection/napari-feature-classifier#21]
Hi @jluethi 

I tried your plugin. 
First, I created a classifier on one image.
Then, I loaded a new image + mask. Selected `Load Classifier` and specified the classifier and the features .csv of the new image.
I showed the results I expected in the viewer.

But when I exported the classifier results, the csv file did not correspond to what I saw in the napari viewer.
I.e. the counts for the two classes do not match what I see in the viewer.
In the attached image, label 4 is classified as green (class 2) in the viewer but in the csv it is class 1.
Or label 24 is red (class 1) in the viewer but the csv is class 2.
See those examples in the image (class 2 are the 'rare' cells).

In addition the csv has a 'train' column that has some non-zero values. I did not expect that, since this is an image that was not used for training.

Is this a bug or am I doing something wrong?
I'm running `napari-feature-classifier v0.0.1`.

Further, after clicking `Export Classifier Results`, I get following console info/warning (not sure if it is related):
```
INFO: Exporting classifier results
INFO: F1 score on test set: 0.42857142857142855
Annotations split into 19 training and 4 test samples.
Training set contains 10 annotations for class 1, 9 annotations for class 2.
Test set contains 3 annotations for class 1, 1 annotations for class 2.
C:\Users\Microscopy\.conda\envs\napari\lib\site-packages\napari_feature_classifier\classifier.py:312: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`!
```

<img width="1281" alt="Screenshot 2023-02-08 at 16 47 02" src="https://user-images.githubusercontent.com/29227811/217582979-8e990c05-fe8e-4d07-97df-ea995e87644a.png">

```napari: 0.4.17
Platform: Windows-10-10.0.19045-SP0
Python: 3.9.15 (main, Nov 4 2022, 16:35:55) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.23.4
SciPy: 1.9.3
Dask: 2022.11.0
VisPy: 0.11.0
magicgui: 0.6.0
superqt: 0.4.0
in-n-out: 0.1.6
app-model: 0.1.1
npe2: 0.6.1

OpenGL:
- GL version: 4.6.0 NVIDIA 526.67
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 3008x1692, scale 1.0```

**Comment by jluethi** [comment]
Hey Loic,

Thanks for the bug report and for describing in detail what you're doing.

> But when I exported the classifier results, the csv file did not correspond to what I saw in the napari viewer.

When exporting the classifier results, you're getting results for all the images it has been trained on, if I remember correctly. The `path` column describes which image a given label belongs to. Can you check whether, when you scroll down in the csv file, you find the second (third, fourth, or what image you are on) and check whether the prediction is what you expect for the given label there?

If that's the case, I'll need to document better what's happening here (or consider how we'll do this in our current refactor). If that's not the case, we actually have a tricky bug here I need to look into :)

> In addition the csv has a 'train' column that has some non-zero values. I did not expect that, since this is an image that was not used for training.

My suspicion is that what you see at the top is the data from the first image, where you actually trained. Confirm with the `path` variable to check.

Also, thanks for sharing the warning. Shouldn't be related :)

**Comment by loicsauteur** [comment]
Hi @jluethi 

Thanks for the answer.

> When exporting the classifier results, you're getting results for all the images it has been trained on, if I remember correctly. The path column describes which image a given label belongs to. Can you check whether, when you scroll down in the csv file, you find the second (third, fourth, or what image you are on) and check whether the prediction is what you expect for the given label there?

Yes, you are right. Sorry, I did not expect that it would export all data from all images used. And I did not pay attention to the `path`...
So also the `train` values make sense, they are from the image I trained on...

Thanks again for clarifying!

**Comment by jluethi** [comment]
Thanks for raising the issue! I'll think about how we'll handle this in the refactored version and, if we choose the same approach (sometimes a useful user-flow), then I'll have to think on how to best document this :) 

It's an easy point for potential confusion, as it may not be the expected behavior.
